services:
  nginx:
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    env_file: .env
    networks:
      - wordpress-net
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress-net
    depends_on:
      - mariadb
    restart: unless-stopped
    expose: 
      - "9000"

  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - wordpress-net
    restart: unless-stopped
    expose:
      - "3306"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ogregoir/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ogregoir/data/mariadb'
  
networks:
  wordpress-net:
    driver: bridge
