version : '3'

services:
  nginx:
    build: ./requirement/nginx
    ports:
      - "443:443"
    volumes:
      - ./volumes/nginx:/etc/nginx
    networks:
      - wordpress-net
    restart: always

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - ./volumes/wordpress:/var/www/html
    networks:
      - wordpress-net
    depends_on:
      - mariadb
    restart: always

  mariadb :
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "oce"
      MYSQL_DATABASE: "maria"
      MYSQL_USER: "invited"
      MYSQL_PASSWORD: "oce"
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - wordpress-net
    restart: always
  
networks:
  wordpress-net:
    driver: bridge
